version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/app
    steps:
      - run: 'node -v'
      - run: 'npm -v'
      - checkout
      - run: 'npm ci'
      - run: 'npm test'
